name: sqlrules
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - comm=0.1.2=py38h06a4308_0
  - cryptography=41.0.7=py38hdda0065_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - greenlet=3.0.1=py38h6a678d5_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py38h2f386ee_0
  - ipython=8.12.2=py38h06a4308_0
  - ipython-sql=0.3.9=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.5.0=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - prettytable=3.5.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pymysql=1.0.2=py38h06a4308_1
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py38h06a4308_0
  - pyzmq=25.1.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlalchemy=1.4.51=py38h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sqlparse=0.4.4=py38h06a4308_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.9.0=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
prefix: /home/fungi/anaconda3/envs/sqlrules
